[project]
name = "boost-ml-agents"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "tsyu12345", email = "syukut@gmail.com" }
]
dependencies = [
    "mlagents>=1.0.0",
    "torch==1.13.1+cu116",
    "torchaudio==0.13.1",
    "torchvision==0.14.1+cu116",
    "numpy==1.22.4",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/boost_ml_agents"]

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu116"
type = "index"
